### ISSUE TITLE
No funciona app-generate-crud en Windows

### ISSUE THREAD

**Issue by robertovillarejo** [kukulkan-project/kukulkan-shell#6]
Al intentar generar un CRUD con `app-generate-crud` se lanza una excepción. 
Parece que, en Windows, la directiva `include` de FreeMarker no resuelve correctamente la ruta y por tanto no encuentra la plantilla para incluirla. 

```
[DEBUG] : Interpreting file C:\Users\roberto.villarejo\Downloads\prueba\demojpa\test.3k
[DEBUG] : Parsing the column persona
[DEBUG] : Trim the value persona
[INFO ] : Processing File...
[DEBUG] : visitDomainModelElement: mx.infotec.dads
[DEBUG] : repositoryLayerTask for dommain
[DEBUG] : visitDomainModelElement for mx.infotec.dads
[DEBUG] : Domain
[ERROR] : Error executing FreeMarker template
freemarker.core._MiscTemplateException: Template inclusion failed (for parameter value "types/text"):
Template not found for name "types/text".
The name was interpreted by this TemplateLoader: org.springframework.ui.freemarker.SpringTemplateLoader@1b97d1ff.

----
FTL stack trace ("~" means nesting-related):
        - Failed at: #include "types/text" parse=true  [in template "rest-spring-jpa\\database\\liquibase\\changelog\\added_entity.xml.ftl" at line 39, column 41]
----
        at freemarker.core.Include.accept(Include.java:164)
        at freemarker.core.Environment.visit(Environment.java:325)
        at freemarker.core.Environment.visit(Environment.java:331)
        at freemarker.core.Environment.visit(Environment.java:331)
        at freemarker.core.Environment.visit(Environment.java:367)
        at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:317)
        at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
        at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:242)
        at freemarker.core.Environment.visitIteratorBlock(Environment.java:635)
        at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:107)
        at freemarker.core.IteratorBlock.accept(IteratorBlock.java:93)
        at freemarker.core.Environment.visit(Environment.java:361)
        at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:317)
        at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
        at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:242)
        at freemarker.core.Environment.visitIteratorBlock(Environment.java:635)
        at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:107)
        at freemarker.core.IteratorBlock.accept(IteratorBlock.java:93)
        at freemarker.core.Environment.visit(Environment.java:361)
        at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:317)
        at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
        at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:242)
        at freemarker.core.Environment.visitIteratorBlock(Environment.java:635)
        at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:107)
        at freemarker.core.IteratorBlock.accept(IteratorBlock.java:93)
        at freemarker.core.Environment.visit(Environment.java:325)
        at freemarker.core.Environment.visit(Environment.java:331)
        at freemarker.core.Environment.process(Environment.java:304)
        at freemarker.template.Template.process(Template.java:382)
        at mx.infotec.dads.kukulkan.engine.util.TemplateUtil.processTemplate(TemplateUtil.java:117)
        at mx.infotec.dads.kukulkan.engine.util.TemplateUtil.processTemplate(TemplateUtil.java:100)
        at mx.infotec.dads.kukulkan.engine.templating.service.TemplateServiceImpl.createGeneratedElement(TemplateServiceImpl.java:73)
        at mx.infotec.dads.kukulkan.generator.layers.data.liquibase.LiquibaseLayerImpl.visitEntity(LiquibaseLayerImpl.java:98)
        at mx.infotec.dads.kukulkan.engine.model.AbstractNavigableLayer.doForEachEntity(AbstractNavigableLayer.java:96)
        at mx.infotec.dads.kukulkan.engine.model.AbstractNavigableLayer.doForEachDataModelGroupTemplate(AbstractNavigableLayer.java:76)
        at mx.infotec.dads.kukulkan.engine.model.AbstractNavigableLayer.process(AbstractNavigableLayer.java:62)
        at mx.infotec.dads.kukulkan.engine.service.EngineGenerator.lambda$process$1(EngineGenerator.java:70)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at mx.infotec.dads.kukulkan.engine.service.EngineGenerator.process(EngineGenerator.java:70)
        at mx.infotec.dads.kukulkan.shell.commands.kukulkan.AppGeneration.appGenerateCrud(AppGeneration.java:103)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:216)
        at org.springframework.shell.Shell.evaluate(Shell.java:169)
        at org.springframework.shell.Shell.run(Shell.java:134)
        at org.springframework.shell.jline.InteractiveShellApplicationRunner.run(InteractiveShellApplicationRunner.java:84)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:723)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:713)
        at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
        at mx.infotec.dads.kukulkan.KukulkanShellApplication.main(KukulkanShellApplication.java:21)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: freemarker.template.TemplateNotFoundException: Template not found for name "types/text".
The name was interpreted by this TemplateLoader: org.springframework.ui.freemarker.SpringTemplateLoader@1b97d1ff.
        at freemarker.template.Configuration.getTemplate(Configuration.java:2701)
        at freemarker.core.Environment.getTemplateForInclusion(Environment.java:2517)
        at freemarker.core.Include.accept(Include.java:162)
        ... 57 common frames omitted

```

**Comment by robertovillarejo** [comment]
Según la [documentación de FreeMarker](https://freemarker.apache.org/docs/ref_directive_include.html) el parámetro _path_ de la directiva **include** puede recibir rutas relativas o absolutas.

_The path parameter can be a relative path like "foo.ftl" and "../foo.ftl", or an absolute like "/foo.ftl"_

Sin embargo, dependiendo del sistema operativo el parámetro _path_ se resuelve o no.
Haciendo algunas pruebas:

|                                                      	| Ubuntu 	| Windows 	|
|------------------------------------------------------	|--------	|---------	|
| ./types/template.ftl                                 	| Sí     	| No      	|
| */types/template.ftl                                 	| Sí     	| No      	|
| rest-spring-jpa/backend/database/types/template.ftl  	| No     	| Sí      	|
| /rest-spring-jpa/backend/database/types/template.ftl 	| Sí     	| Sí      	|

Ésta última es la ruta absoluta de la plantilla (absoluta a partir de la carpeta definida como tal en la configuración de FreeMarker que en este caso es **templates**)

Por ahora, se optará por utilizar la ruta absoluta en la directiva **include** en las plantillas ftl.

**Comment by robertovillarejo** [comment]
Resuelto en [Update CRUD templates to absolute path](https://github.com/kukulkan-project/kukulkan-generator-angularjs/commit/fbef60a4c0e6095297422db50d817674ba0feca9)
